# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commways',
            name='way',
            field=models.CharField(max_length=21),
        ),
    ]
