# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20160603_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nc_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
