# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20160605_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Vorname'),
        ),
    ]
