# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0008_auto_20160605_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnstatus', models.CharField(choices=[('+', 'Teilnahme'), ('0', 'Unklar'), ('-', 'Absage')], default='0', max_length=1)),
                ('text', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventplanner.Event')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.User')),
            ],
        ),
    ]
