# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventplanner', '0002_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='groups',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Group'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.User'),
        ),
    ]
