# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20160605_1751'),
        ('eventplanner', '0004_auto_20160605_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='groups',
        ),
        migrations.AddField(
            model_name='invite',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Group'),
        ),
        migrations.RemoveField(
            model_name='invite',
            name='user',
        ),
        migrations.AddField(
            model_name='invite',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.User'),
        ),
    ]
