# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventplanner', '0005_auto_20160605_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.CharField(default='basti', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='groups',
            field=models.ManyToManyField(blank=True, to='contacts.Group'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ManyToManyField(blank=True, to='contacts.User'),
        ),
    ]
